export enum EWSMessageType {
    INITIALISE = 'INITIALISE',
    START_STREAM = 'START_STREAM',
    STOP_STREAM = 'STOP_STREAM',
    START_PLAYLIST = 'START_PLAYLIST',
    STOP_PLAYLIST = 'STOP_PLAYLIST',
    START_SCHEDULE = 'START_SCHEDULE',
    STOP_SCHEDULE = 'STOP_SCHEDULE',
    START_AUDIO = 'START_AUDIO',
    START_VIDEO = 'START_VIDEO',
    GET_AUDIO_INFO = 'GET_AUDIO_INFO',
    START_ALL_DISPLAYS = "START_ALL_DISPLAYS"

}